### PR TITLE
add scenario name to configuration that can be used for plotting example

### PR DESCRIPTION
**Pull request by awirb**

### CODE REVIEW

**Comment by fso42** [comment]
@awirb: Why not just use the simulation name?

**Review by matthiasto — COMMENTED** [review]
What does this scenario name say? can you give an example?

**Comment by awirb** [comment]
It can be used to gather multiple simulations for example if you do a probRun, and vary multiple variables one after the other, and you want to plot some result parameter vs the other and group the ones where parameter a was varied and those where parameter b was varied.

**Review by fso42 — APPROVED** [review]
Maybe squash the commits to just one...

**Pull request merged**
